version: '3.8'

services:
  backend:
    build: ./backend
    container_name: login-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - JWT_SECRET=mi-secreto-super-seguro-para-jwt
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    container_name: login-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2gb
    networks:
      - app-network
    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=300

networks:
  app-network:
    driver: bridge
